# Generated by Django 3.1.7 on 2021-03-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pick',
            new_name='profile_pic',
        ),
    ]
